// <auto-generated />
using System;
using AssetManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621174800_UserUpdatedat")]
    partial class UserUpdatedat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManagementSystem.Models.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.HasIndex("AssignedToUserId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000001"),
                            AssetTag = "LAP-001",
                            AssignedToUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Laptop",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Name = "Dell Latitude 5440",
                            SerialNumber = "DL5440-0001",
                            Status = "Assigned"
                        },
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000002"),
                            AssetTag = "LAP-002",
                            Category = "Laptop",
                            Condition = "New",
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Name = "Dell Latitude 5440",
                            SerialNumber = "DL5440-0002",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("a1111111-0000-0000-0000-000000000003"),
                            AssetTag = "LAP-003",
                            Category = "Laptop",
                            Condition = "Damaged",
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Name = "MacBook Pro 14\"",
                            SerialNumber = "MBP14-0003",
                            Status = "Maintenance"
                        },
                        new
                        {
                            Id = new Guid("a2222222-0000-0000-0000-000000000001"),
                            AssetTag = "MON-001",
                            Category = "Monitor",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Name = "Dell UltraSharp 27\"",
                            SerialNumber = "DU27-0001",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("a2222222-0000-0000-0000-000000000002"),
                            AssetTag = "MON-002",
                            Category = "Monitor",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Name = "Dell UltraSharp 27\"",
                            SerialNumber = "DU27-0002",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("a2222222-0000-0000-0000-000000000003"),
                            AssetTag = "MON-003",
                            Category = "Monitor",
                            Condition = "Lost",
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = true,
                            Name = "LG UltraWide 34\"",
                            SerialNumber = "LGUW34-0003",
                            Status = "Retired"
                        },
                        new
                        {
                            Id = new Guid("a3333333-0000-0000-0000-000000000001"),
                            AssetTag = "PHN-001",
                            Category = "Phone",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Name = "iPhone 14",
                            SerialNumber = "IP14-0001",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("a3333333-0000-0000-0000-000000000002"),
                            AssetTag = "PHN-002",
                            Category = "Phone",
                            Condition = "New",
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Name = "iPhone 14",
                            SerialNumber = "IP14-0002",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("a4444444-0000-0000-0000-000000000001"),
                            AssetTag = "KEY-001",
                            Category = "SecurityKey",
                            Condition = "New",
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Name = "YubiKey 5C",
                            SerialNumber = "YK5C-0001",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("a4444444-0000-0000-0000-000000000002"),
                            AssetTag = "KEY-002",
                            Category = "SecurityKey",
                            Condition = "Good",
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = true,
                            Name = "YubiKey 5C",
                            SerialNumber = "YK5C-0002",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Entities.AssetHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId");

                    b.ToTable("AssetHistories");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Entities.CheckoutRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssetCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AssignedAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FulfilledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestType")
                        .HasColumnType("int");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAssetId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("CheckoutRequests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-0000-0000-0000-000000000001"),
                            AssetCategory = "Laptop",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Reason = "Need a backup laptop for travel",
                            RequestType = 0,
                            RequestedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Pending",
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b1111111-0000-0000-0000-000000000002"),
                            AssetCategory = "Phone",
                            CreatedAt = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Reason = "Existing phone screen is cracked",
                            RequestType = 0,
                            RequestedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Pending",
                            UpdatedAt = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b1111111-0000-0000-0000-000000000003"),
                            AssetCategory = "Monitor",
                            AssignedAssetId = new Guid("a2222222-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Reason = "Returning second monitor, no longer needed",
                            RequestType = 1,
                            RequestedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Pending",
                            UpdatedAt = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2222222-0000-0000-0000-000000000001"),
                            ApprovedAt = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            AssetCategory = "SecurityKey",
                            CreatedAt = new DateTime(2025, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Reason = "MFA hardware key for new system rollout",
                            RequestType = 0,
                            RequestedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Approved",
                            UpdatedAt = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2222222-0000-0000-0000-000000000002"),
                            ApprovedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            AssetCategory = "Monitor",
                            CreatedAt = new DateTime(2025, 2, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = true,
                            Reason = "Second monitor requested for home office",
                            RequestType = 0,
                            RequestedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Approved",
                            UpdatedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b3333333-0000-0000-0000-000000000001"),
                            AssetCategory = "Tablet",
                            CreatedAt = new DateTime(2025, 2, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Reason = "Would like a tablet for note-taking in meetings",
                            RejectedAt = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestType = 0,
                            RequestedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Rejected",
                            UpdatedAt = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b6666666-0000-0000-0000-000000000001"),
                            AssetCategory = "SecurityKey",
                            AssignedAssetId = new Guid("a4444444-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Reason = "Requesting to return security key, no longer assigned to this project",
                            RejectedAt = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            RequestType = 1,
                            RequestedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Rejected",
                            UpdatedAt = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b4444444-0000-0000-0000-000000000001"),
                            ApprovedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            AssetCategory = "Laptop",
                            AssignedAssetId = new Guid("a1111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            FulfilledAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Reason = "Primary laptop for daily work",
                            RequestType = 0,
                            RequestedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Fulfilled",
                            UpdatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b5555555-0000-0000-0000-000000000001"),
                            AssetCategory = "Monitor",
                            AssignedAssetId = new Guid("a2222222-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Reason = "Temporary monitor for project sprint, returning now",
                            RequestType = 1,
                            RequestedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ReturnedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ReviewedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Returned",
                            UpdatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b7777777-0000-0000-0000-000000000001"),
                            AssetCategory = "Monitor",
                            AssignedAssetId = new Guid("a2222222-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Reason = "Requested to return monitor, changed mind",
                            RequestType = 1,
                            RequestedByUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = "Cancelled",
                            UpdatedAt = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b8888888-0000-0000-0000-000000000001"),
                            AssetCategory = "Headset",
                            CreatedAt = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsArchived = false,
                            Reason = "Requested headset for calls, no longer needed",
                            RequestType = 0,
                            RequestedByUserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = "Cancelled",
                            UpdatedAt = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "admin@test.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "manager@test.com",
                            FirstName = "Manager",
                            IsActive = true,
                            LastName = "User",
                            Role = "AssetManager"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "employee@test.com",
                            FirstName = "Employee",
                            IsActive = true,
                            LastName = "User",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Entities.Asset", b =>
                {
                    b.HasOne("AssetManagementSystem.Models.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId");

                    b.Navigation("AssignedToUser");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Entities.AssetHistory", b =>
                {
                    b.HasOne("AssetManagementSystem.Models.Entities.Asset", "Asset")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagementSystem.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Entities.CheckoutRequest", b =>
                {
                    b.HasOne("AssetManagementSystem.Models.Entities.Asset", "AssignedAsset")
                        .WithMany()
                        .HasForeignKey("AssignedAssetId");

                    b.HasOne("AssetManagementSystem.Models.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagementSystem.Models.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId");

                    b.Navigation("AssignedAsset");

                    b.Navigation("RequestedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Entities.Asset", b =>
                {
                    b.Navigation("HistoryEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
